version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-net

  rbac-service:
    build:
      context: .
      dockerfile: rbac-service/Dockerfile
    container_name: rbac-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
